# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 20:20
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('curso', models.CharField(max_length=100)),
                ('candidato_id', models.CharField(max_length=200)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criador', models.CharField(max_length=250)),
                ('titulo', models.CharField(max_length=500)),
                ('descricao', models.CharField(max_length=100)),
                ('imagem', models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/7/7b/Minerva_UFRJ_Oficial.png', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome', models.CharField(max_length=256)),
                ('telefone', models.CharField(max_length=256)),
                ('nascimento', models.CharField(max_length=256)),
                ('e_aluno', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ofertas.Usuario')),
                ('user_id', models.CharField(max_length=1024)),
                ('estadoCivil', models.CharField(max_length=256)),
                ('curso', models.CharField(max_length=256)),
                ('periodo', models.CharField(max_length=2)),
                ('CRA', models.CharField(max_length=7)),
                ('objetivo', models.CharField(max_length=256)),
                ('formacao', models.CharField(max_length=256)),
                ('experiencia', models.CharField(max_length=1024)),
                ('habilidade', models.CharField(max_length=1024)),
                ('identificador', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
                'abstract': False,
            },
            bases=('ofertas.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorRecrutador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ofertas.Usuario')),
                ('departamento', models.CharField(max_length=256)),
                ('admDepartamento', models.BooleanField(default=False)),
                ('identificador', models.CharField(max_length=1024)),
                ('esta_validado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
                'abstract': False,
            },
            bases=('ofertas.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofertas.Oferta'),
        ),
    ]
