# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=250)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criador', models.CharField(max_length=250)),
                ('titulo', models.CharField(max_length=500)),
                ('descricao', models.CharField(max_length=100)),
                ('imagem', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofertas.Oferta'),
        ),
    ]
