# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='imagem',
            field=models.CharField(max_length=10000),
        ),
    ]
